### ISSUE TITLE
[TITLE] The Silence - 81021447

### ISSUE THREAD

**Issue by MapleCCC** [jessuni/popcorn-issues#4]
- [x] I have read the guidelines.
 - [x] I have checked the issue list. No one has reported this title before.

**Content**
- title: The Silence
- NetflixID: 81021447
- Which link is wrong?
  - [ ] IMDb: 
  - [ ] RottenTomatoes:
  - [x] Douban: https://movie.douban.com/subject/1293544/
  
- The right link:
  - IMDb:
  - RottenTomatoes:
  - Douban: https://movie.douban.com/subject/27050133/

**Additional context**

- [x] I have double checked to make sure the content is filled and formatted.

**Comment by jessuni** [comment]
Thanks for the contribution! Currently the extension is in the middle of some transition, so your submission might not take effect. It will get back to normal, however, once version 0.3.0 gets published. In the meantime, don't hold back and you're welcome to submit more if you have found more mismatches.
