### ISSUE TITLE
[TITLE]Life's Punchline - 81506767

### ISSUE THREAD

**Issue by Star229** [jessuni/popcorn-issues#7]
- [x] I have read the guidelines.
 - [x] I have checked the issue list. No one has reported this title before.

**Content**
- title: Life's Punchline
- NetflixID: 81506767
- Which link is wrong?
  - [x] IMDb: https://www.imdb.com/title/tt5442430/
  - [ ] RottenTomatoes:
  - [x] Douban: https://movie.douban.com/subject/26718838/
  
- The right link:
  - IMDb: https://www.imdb.com/title/tt15073094
  - RottenTomatoes:
  - Douban:https://movie.douban.com/subject/35358556/

**Additional context**

- [x] I have double checked to make sure the content is filled and formatted.

**Comment by jessuni** [comment]
You made it to the right format! 🎉

Thanks for the contribution! Currently the extension is in the middle of some transition, so your submission might not take effect. It will get back to normal, however, once version 0.3.0 gets published. In the meantime, don't hold back and you're welcome to submit more if you have found more mismatches.
